### ISSUE TITLE
Super 3-D Noah's Ark (371180)

### ISSUE THREAD

**Issue by MicrosoftTakeover** [dreamer/steam-dos#13]
## Compatibility Report
https://store.steampowered.com/app/371180
https://www.protondb.com/app/371180

### System Information
- Linux distribution: Arch
- Kernel: 5.1.14-zen1-2-zen
- Desktop: i3
- DOSBox: version 0.74-2

### Report
- The game runs out of the box: No

### Configuration changes
n/a

### Report
This game is a special case. It has a native Linux version, but also includes the original DOS version as well. This file is called 'noah3dos.exe' in the game's directory which can easily be run with DOSBox directly, but steam-dos doesn't seem to know how to handle it.

**Comment by dreamer** [comment]
I just pushed possible fix 9fbd27cae25d44445b3b4ba11a4fd4722b5c0bcb to branch `noah`. Can you test this version? [steam-dos.zip](https://github.com/dreamer/steam-dos/files/3334128/steam-dos.zip)

If it'll work correctly, I'll include it in next release.

**Comment by dreamer** [comment]
Version that fixes ALSA sequencer list bug: [steam-dos.zip](https://github.com/dreamer/steam-dos/files/3336164/steam-dos.zip)

**Comment by dreamer** [comment]
Fixed in 0.4.0 release.
