### ISSUE TITLE
Support auto-download of game resources

### ISSUE THREAD

**Issue by dreamer** [dreamer/steam-dos#17]
For downloading official patches or mods that bring back vanilla DOS support to the game user already owns.

First game that needs it is Fallout 1, as DOS support is included in official DOS patch, but not in Steam version out of the box.

**Comment by Faalagorn** [comment]
Very WIP version of this for Fallout is available in [steam-dos/tree/fallout](/dreamer/steam-dos/tree/fallout).

**Comment by dreamer** [comment]
First working version implemented in 0.4.2 release :)

Will be improved as/if needed - closing for now.
