### ISSUE TITLE
reporting whitelist candidates

### ISSUE THREAD

**Issue by m-svo** [dreamer/steam-dos#4]
Did not see any whitelist, are reports needed?
I tested:
HeXen: Beyond Heretic (2360)
HeXen: Deathkings of the Dark Citadel (2370)
Heretic: Shadow of the Serpent Riders (2390)
they all work with no issues with steam-dos 0.2.1 with overlay disabled
with overlay enabled on wide screen (16:9) there are blinking steam pop ups in right bottom corner

**Comment by dreamer** [comment]
I was thinking about this for a while and decided to use similar system as Proton does - an issue with compatibility report per game (and separate report per GOG game). This way it is possible to track what games were actually tested and prioritize bugfixes.

I just created a new issue template for it (and one compatibility report myself) - I think it will be a bit more convenient to fill than template Proton uses.

This overlay issue seems to be a common one - please report it as separate bug (and link to it from compatibility reports).

**Comment by m-svo** [comment]
Thanks, will do!

**Comment by dreamer** [comment]
@m-svo FYI - I decided, that creating whole issue reports might be too "heavy". Created a simple table with compatibility reports instead: https://github.com/dreamer/steam-dos/wiki/Compatibility-reports-(Steam)
